/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package eu.parkHere.challenge.api

import eu.parkHere.challenge.model.ReservationRequest
import eu.parkHere.challenge.model.ReservationResponse
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface ApiApi {

    @Operation(
        tags = ["Reservation",],
        summary = "Create a reservation for a parking spot",
        operationId = "createReservation",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Successful reservation", content = [Content(schema = Schema(implementation = ReservationResponse::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/parking-lots/{parking-lot-id}/reservations"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createReservation(@Parameter(description = "The ID of the parking lot", required = true) @PathVariable("parking-lot-id") parkingLotId: kotlin.Int,@Parameter(description = "", required = true) @Valid @RequestBody reservationRequest: ReservationRequest): ResponseEntity<ReservationResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
