/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eu.parkHere.challenge.api

import com.fasterxml.jackson.annotation.JsonProperty

import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.reactive.function.client.WebClientResponseException
import org.springframework.http.codec.json.Jackson2JsonDecoder
import org.springframework.http.codec.json.Jackson2JsonEncoder
import org.springframework.http.ResponseEntity
import org.springframework.http.MediaType
import reactor.core.publisher.Mono
import org.springframework.util.LinkedMultiValueMap

import eu.parkHere.challenge.model.ParkingSpot
import org.openapitools.client.infrastructure.*

class ConfigurationApi(client: WebClient) : ApiClient(client) {

    constructor(baseUrl: String) : this(WebClient.builder()
        .baseUrl(baseUrl)
        .codecs {
            it.defaultCodecs().jackson2JsonEncoder(Jackson2JsonEncoder(Serializer.jacksonObjectMapper, MediaType.APPLICATION_JSON))
            it.defaultCodecs().jackson2JsonDecoder(Jackson2JsonDecoder(Serializer.jacksonObjectMapper, MediaType.APPLICATION_JSON))
        }
        .build()
    )


    @Throws(WebClientResponseException::class)
    fun getParkingSpotsByLot(parkingLotId: kotlin.Int): Mono<kotlin.collections.List<ParkingSpot>> {
        return getParkingSpotsByLotWithHttpInfo(parkingLotId = parkingLotId)
            .map { it.body }
    }

    @Throws(WebClientResponseException::class)
    fun getParkingSpotsByLotWithHttpInfo(parkingLotId: kotlin.Int): Mono<ResponseEntity<kotlin.collections.List<ParkingSpot>>> {
        val localVariableConfig = getParkingSpotsByLotRequestConfig(parkingLotId = parkingLotId)
        return request<Unit, kotlin.collections.List<ParkingSpot>>(
            localVariableConfig
        )
    }

    fun getParkingSpotsByLotRequestConfig(parkingLotId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        val params = mutableMapOf<String, Any>(
            "parking-lot-id" to parkingLotId,
        )

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/parking-lots/{parking-lot-id}",
            params = params,
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

}
