/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package eu.parkHere.challenge.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param priority 
 * @param name 
 */


data class ParkingSpot (

    @get:JsonProperty("id")
    val id: kotlin.Int,

    @get:JsonProperty("priority")
    val priority: kotlin.Int,

    @get:JsonProperty("name")
    val name: kotlin.String? = null

) {


}

